# Write your code here :-)
print ("Welcome to Eric's coffee shop")
print ("I'm glad to see you")
name = input ("please enter your name: ")
drink = input ("Please enter your drink: ")
flavor = input ("Please enter your flavor: ")
topping = input ("please enter your topping: ")

#print ("Here is your order,",name)
#print ("Main product:" , drink)
#print ("Your flavor:", flavor)
#print ("Your topping:", topping)
print ("Here is your order,", name)
print (drink, "with", flavor, "tasty and with", topping, "topping",)
print ("Bedankt voor uw bestelling")
print ("fijne avond en tot ziens")
print ("wacht op jouw bestelling")
